export const topicList = [
  { id: "531", title: "Get Screened" },
  { id: "30533", title: "Get Enough Sleep" },
  { id: "30537", title: "Get Your Cholesterol Checked" },
  { id: "30538", title: "Choose the Right Birth Control" },
  { id: "30539", title: "Eat Healthy" },
  { id: "30540", title: "Get Your Well-Woman Visit Every Year" },
  { id: "30541", title: "Men: Take Charge of Your Health" },
  { id: "30546", title: "Take Steps to Prevent Type 2 Diabetes" },
  { id: "30547", title: "Get Active" },
  { id: "30558", title: "Drink Alcohol Only in Moderation" },
  { id: "30560", title: "Manage Stress" },
  { id: "30588", title: "Quitting Smoking: Conversation Starters" },
  { id: "30604", title: "Depression: Conversation Starters" },
  { id: "30606", title: "Alcohol Use: Conversation Starters" },
  { id: "30610", title: "Quit Smoking" },
  { id: "30614", title: "Testing for Syphilis: Questions for the Doctor" },
  { id: "33303", title: "Talk with Your Doctor About Drug Misuse" },
  { id: "33304", title: "Drug Misuse: Conversation Starters" },
  { id: "34691", title: "Get Your Child Screened for Anxiety" },
  { id: "34692", title: "Anxiety: Conversation Starters" },
];
