export const topicList = [
  { id: "20", title: "Mental Health and Relationships" },
  { id: "21", title: "Nutrition" },
  { id: "24", title: "Physical Activity" },
  { id: "25", title: "Regular Checkups" },
  { id: "26", title: "Safety" },
  { id: "27", title: "Screening Tests" },
  { id: "28", title: "Sexual Health" },
  { id: "30", title: "Talking with the Doctor" },
  { id: "98", title: "Helping a Loved One" },
  { id: "99", title: "Doctor Visits" },
  { id: "100", title: "Helping a Loved One" },
  { id: "102", title: "Helping a Loved One" },
  { id: "109", title: "Mental Health" },
  { id: "110", title: "Healthy Relationships" },
  { id: "111", title: "Helping a Loved One" },
  { id: "126", title: "Healthy Living" },
  { id: "314", title: "Substance Use and Misuse" },
];
